import React, { useEffect, useState } from "react";

const UsernameAndAvatar = () => {
    const [chosenAvatarId, setChosenAvatarId] = useState(null);
    const [randomUsername, setRandomUsername] = useState(null);

    useEffect(() => {
        /* Fikk AI til å lage en liste med random navn */
        fetch("/usernames.json")
            .then(response => response.json())
            .then(data => {
                const randomIndex = Math.floor(Math.random() * data.generatedUsernames.length);
                setRandomUsername(data.generatedUsernames[randomIndex]);
            })
            .catch(error => {
                console.error("Error fetching usernames:", error);
                // setter brukernavn til "Burning Archer" hvis error
                setRandomUsername("Burning Archer");
            });
    }, []);
    

    const handleAvatarClick = (avatarId) => {
        setChosenAvatarId(avatarId);
    };

    function handleContinueClick() {
        if (chosenAvatarId != null) {
            console.log("You picked: Mario!")
        } else {
            console.log("Please chose an avatar first.")
        }
    }

    /* avatar-data, kan og brude sikkert gjøres på en annen måte */
    const avatars = [
        { id: 'viking1', src: "/Viking.png", alt: "avatar of viking" },
        { id: 'mario-head-img-2', src: "/mario.png", alt: "avatar of mario-head" },
        { id: 'mario-head-img-3', src: "/mario.png", alt: "avatar of mario-head" },
        { id: 'mario-head-img-4', src: "/mario.png", alt: "avatar of mario-head" },
        { id: 'mario-head-img-5', src: "/mario.png", alt: "avatar of mario-head" },
        { id: 'viking2', src: "/Viking.png", alt: "avatar of viking" },
    ];

    return (
        <section className="name-and-avatar-container">
            <div className="info-box">
                <p>Waiting for all players!</p>
                <p>GameRoom:</p>
                <p>4400AB</p>
            </div>
            <div className="name-container">
                <h3>Your autogenerated name:</h3>
                <p>'{randomUsername}'</p>
            </div>
            
            <div>
            <h3>Choose an avatar:</h3>
            <div className="avatars-container">
                {avatars.map(avatar => (
                    <img
                        key={avatar.id}
                        src={avatar.src}
                        alt={avatar.alt}
                        id={avatar.id}
                        onClick={() => handleAvatarClick(avatar.id)}
                        style={{ 
                            transform: chosenAvatarId === avatar.id ? "scale(1.5)" : "scale(1)",
                            zIndex: chosenAvatarId === avatar.id ? "1" : "0",
                            width: "100px",
                        }}
                    />
                ))}
            </div></div>
            <button className="continue-button" onClick={handleContinueClick}>CONTINUE</button>
        </section>
    );
};

export default UsernameAndAvatar;
