import React, { useEffect, useState } from "react";
import { useNavigate } from 'react-router-dom';
import vikingAvatar from "../assets/Viking.png";
import SwordmanSUpAvatar from '../assets/SwordmanSUp.png';
import WitchAvatar from '../assets/Witch.png';
import SwordWomanAvatar from '../assets/SwordWoman.png';
import ArcherAvatar from '../assets/Archer.png';
import SwordmanSDownAvatar from '../assets/SwordmanSDown.png';

const UsernameAndAvatar2 = ({ currentPage, setCurrentPage }) => {
    const [chosenAvatarId, setChosenAvatarId] = useState(null);
    const [randomUsername, setRandomUsername] = useState(null);
    const navigate = useNavigate(); // Use navigate for programmatic navigation

    const avatars = [
        { id: 'viking1', src: vikingAvatar, alt: "avatar of viking" },
        { id: 'swordmanUp', src: SwordmanSUpAvatar, alt: "avatar of swordman" },
        { id: 'witch', src: WitchAvatar, alt: "avatar of witch" },
        { id: 'SwordWoman', src: SwordWomanAvatar, alt: "avatar of pink sword" },
        { id: 'Archer', src: ArcherAvatar, alt: "avatar of archer" },
        { id: 'swordmanDown', src: SwordmanSDownAvatar, alt: "avatar of swordman" },
    ];

    const gameRoomId = "4400AB"

    useEffect(() => {
        fetch("/usernames.json")
            .then(response => response.json())
            .then(data => {
                const randomIndex = Math.floor(Math.random() * data.generatedUsernames.length);
                setRandomUsername(data.generatedUsernames[randomIndex]);
            })
            .catch(error => {
                console.error("Error fetching usernames:", error);
                setRandomUsername("Burning Archer");
            });
    }, []);

    const handleAvatarClick = (avatarId) => {
        setChosenAvatarId(avatarId);
    };

    function handleContinueClick() {
        if (chosenAvatarId != null) {
            navigate('/gameID=1'); // Navigate to the desired route
        } else {
            console.log("Please choose an avatar first.");
        }
    }

    return (
        <div>
            <section className="name-and-avatar-container">
                <div className="info-box">
                    <p>Waiting for all players!</p>
                    <p>GameRoom: {gameRoomId}</p>
                </div>
                <div className="name-container">
                    <h3>Your autogenerated name:</h3>
                    <p>'{randomUsername}'</p>
                </div>
                <div>
                    <h3>Choose your avatar:</h3>
                    <div className="avatars-container">
                        {avatars.map(avatar => (
                            <img
                                key={avatar.id}
                                src={avatar.src}
                                alt={avatar.alt}
                                id={avatar.id}
                                onClick={() => handleAvatarClick(avatar.id)}
                                style={{
                                    transform: chosenAvatarId === avatar.id ? "scale(1.5)" : "scale(1)",
                                    zIndex: chosenAvatarId === avatar.id ? "1" : "0",
                                }}
                            />
                        ))}
                    </div>
                </div>
                <button className="continue-button" onClick={handleContinueClick}>CONTINUE</button>
            </section>
        </div>
    );
};

export default UsernameAndAvatar2;
